=== thuyle2000/2302.E1/6.XMJ/src/d03_product2XSD.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <!-- nut du lieu goc-->
    <xs:element name="product_list">
        <xs:complexType>
            <xs:sequence>
                <!--nut product_list chua cac product -->
                <xs:element name="product" type="productType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <!-- dinh nghia kieu du lieu [productType]-->
    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="quantity" type="xs:positiveInteger" />
            <xs:element name="price" type="priceType" />
            <xs:element name="store" type="storeType" />
        </xs:sequence>
        <xs:attribute name="id" type="productID" />
    </xs:complexType>
    
    <!--dinh nghia kieu du lieu ma so san pham [productID]-->
    <xs:simpleType name="productID">
        <xs:restriction base="xs:string">
            <xs:pattern value="P\d{2}" />
        </xs:restriction>
    </xs:simpleType>
    
    
    <!--dinh nghia kieu du lieu don gia [priceType] -->
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2" />
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="1000" />
        </xs:restriction>
    </xs:simpleType>       

    <!--dinh nghia kieu du lieu kho hang [storeType] -->
    <xs:simpleType name="storeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Saigon" />
            <xs:enumeration value="Ha-noi" />
            <xs:enumeration value="Da-nang" />
        </xs:restriction>
    </xs:simpleType>   
</xs:schema>

=== thuyle2000/2302.E1/6.XMJ/src/d03_product2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="d03_product.css" type="text/css" ?>
<product_list
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='d03_product2XSD.xsd'>
    <product id="P01">
        <name>coca cola</name>
        <quantity>1</quantity>
        <price>12.31</price>
        <store>Da-nang</store>
    </product>
    <product id="P02">
        <name>cake</name>
        <quantity>10</quantity>
        <price>12</price>
        <store>Saigon</store>
    </product>
    <product id="P03">
        <name>beer 333</name>
        <quantity>5</quantity>
        <price>13</price>
        <store>Ha-noi</store>
    </product>

</product_list>
